### ISSUE TITLE
USER STORY: Acceptance Criteria

### ISSUE THREAD

**Issue by CalumRiot** [CalumRiot/love-running#3]
As a **runner** I can **sign up to a newsletter** so that **I receive weekly emails about any new events that Love Running may be organising**

### Acceptance Criteria:
---
- The option is added to the signup page
- A statement should outline what type of content they can expect to receive in the newsletter
- The option should appear as a checkbox next to the email prompt on the sign up page

### Tasks
---
- [ ] Add Front-End HTML to include checkbox for newsletter next to email on sign-up page
- [ ] Add JS to include a pop up when checkbox is selected telling the users the terms of signing up
- [ ] Add Backend Python to take the list of emails that signed up and add them to newsletter spreadsheet
